---
- hosts: all
  user: root
  vars:
    - inventory_path: "{{ INVENTORY_PATH }}"
    - set_profiling: "{{ SET_PROFILING }}"
    - num_hosts: "{{ groups['all'] | length }}"
  tasks:
    - name: set number of forks 
      lineinfile: dest={{ inventory_path }} regexp=^forks line=forks={{ num_hosts }}
      connection: local
    - name: add profiling 
      blockinfile:
        dest: {{ inventory_path }}
        insertafter: "# enable additional callbacks"
        content: |
          callback_whitelist = profile_tasks
      connection: local
      when: inventory_path is defined and set_profiling == "yes"
